import type { Item } from './types';

export const ITEMS: Item[] = [
  {
    id: 'item-1',
    title: 'Vintage Denim Jacket',
    description: 'A classic denim jacket, gently used. Perfect for cool evenings. Ready to find a new home!',
    category: 'Clothes',
    exchangeType: 'donate',
    status: 'available',
    imageUrl: '/imgs/item-1.webp',
    imageHint: 'denim jacket',
    ownerId: 'user-1',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'item-2',
    title: 'Hardcover Novel: "The Starless Sea"',
    description: 'An engaging fantasy novel in like-new condition. Looking to exchange for another fantasy or sci-fi book.',
    category: 'Books',
    exchangeType: 'exchange',
    status: 'available',
    imageUrl: '/imgs/item-2.webp',
    imageHint: 'books stack',
    ownerId: 'user-2',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'item-3',
    title: 'Need to borrow an Electric Kettle',
    description: "Hosting a party this weekend and need an extra electric kettle. Just need it for Saturday. Happy to pick it up anywhere in the city.",
    category: 'Objects',
    exchangeType: 'borrow',
    status: 'available',
    imageUrl: '',
    imageHint: 'electric kettle',
    ownerId: 'user-1',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'item-4',
    title: "Child's Bicycle (16-inch)",
    description: "Our kid has outgrown this bike. It's in good shape with some minor scratches. Perfect for a 4-6 year old. Free to a good home.",
    category: 'Objects',
    exchangeType: 'donate',
    status: 'available',
    imageUrl: '/imgs/item-4.webp',
    imageHint: 'kids bicycle',
    ownerId: 'user-3',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'item-5',
    title: 'Acoustic Guitar',
    description: 'A beginner acoustic guitar. Has a few dings but plays well. Looking to exchange for a ukulele or some board games.',
    category: 'Objects',
    exchangeType: 'exchange',
    status: 'available',
    imageUrl: '/imgs/item-5.webp',
    imageHint: 'acoustic guitar',
    ownerId: 'user-4',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'item-6',
    title: 'Warm Winter Coat',
    description: "Men's large winter coat. Very warm, only used for one season. Donating as I received a new one as a gift.",
    category: 'Clothes',
    exchangeType: 'donate',
    status: 'available',
    imageUrl: '/imgs/item-6.webp',
    imageHint: 'winter coat',
    ownerId: 'user-5',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'item-7',
    title: 'Looking for Catan to borrow',
    description: 'Want to try out Settlers of Catan for a game night with friends. Does anyone have a copy I could borrow for a few days?',
    category: 'Games',
    exchangeType: 'borrow',
    status: 'available',
    imageUrl: '/imgs/item-7.webp',
    imageHint: 'board games',
    ownerId: 'user-6',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'item-8',
    title: 'Yoga Mat',
    description: 'High-quality, non-slip yoga mat. Barely used. Donating because I have two.',
    category: 'Sports',
    exchangeType: 'donate',
    status: 'available',
    imageUrl: '/imgs/item-8.webp',
    imageHint: 'yoga mat',
    ownerId: 'user-7',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'item-9',
    title: 'Request to borrow a Stand Mixer',
    description: "I'm doing some holiday baking and my old hand mixer just died. Would love to borrow a stand mixer for a day or two. Will be very careful with it!",
    category: 'Kitchen',
    exchangeType: 'borrow',
    status: 'available',
    imageUrl: '',
    imageHint: 'stand mixer',
    ownerId: 'user-8',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'item-10',
    title: 'Camping Tent - 4 Person',
    description: 'Spacious 4-person tent. Waterproof and easy to set up. Exchanging for a smaller 2-person tent.',
    category: 'Outdoors',
    exchangeType: 'exchange',
    status: 'available',
    imageUrl: '/imgs/item-10.webp',
    imageHint: 'camping tent',
    ownerId: 'user-9',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'item-11',
    title: 'Set of Dumbbells (5kg)',
    description: 'Pair of 5kg dumbbells. Perfect for home workouts. Donating as I upgraded to a heavier set.',
    category: 'Sports',
    exchangeType: 'donate',
    status: 'available',
    imageUrl: '/imgs/item-11.webp',
    imageHint: 'dumbbells',
    ownerId: 'user-10',
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'item-12',
    title: 'Portable Bluetooth Speaker',
    description: 'Compact and loud Bluetooth speaker with great battery life. Looking to exchange for a good pair of headphones.',
    category: 'Electronics',
    exchangeType: 'exchange',
    status: 'available',
    imageUrl: '/imgs/item-12.webp',
    imageHint: 'bluetooth speaker',
    ownerId: 'user-12',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
