import type { User } from './types';

export const USERS: User[] = [
  {
    id: 'user-1',
    name: 'Alice',
    email: 'alice@circula.demo',
    password: 'password123',
    address: '123 Main St',
    city: 'Greenwood',
    state: 'WA',
    zipcode: '98103',
    country: 'USA',
    reputation: 98,
    completedTransactions: 15,
  },
  {
    id: 'user-2',
    name: 'Bob',
    email: 'bob@circula.demo',
    password: 'password123',
    address: '456 Oak Ave',
    city: 'Greenwood',
    state: 'WA',
    zipcode: '98103',
    country: 'USA',
    reputation: 92,
    completedTransactions: 8,
  },
  {
    id: 'user-3',
    name: 'Charlie',
    email: 'charlie@circula.demo',
    password: 'password123',
    address: '789 Pine Ln',
    city: 'Maple Creek',
    state: 'CA',
    zipcode: '95553',
    country: 'USA',
    reputation: 100,
    completedTransactions: 22,
  },
  {
    id: 'user-4',
    name: 'Diana',
    email: 'diana@circula.demo',
    password: 'password123',
    address: '101 Maple Dr',
    city: 'Maple Creek',
    state: 'CA',
    zipcode: '95553',
    country: 'USA',
    reputation: 95,
    completedTransactions: 12,
  },
  {
    id: 'user-5',
    name: 'Ethan',
    email: 'ethan@circula.demo',
    password: 'password123',
    address: '212 Birch Rd',
    city: 'Oakdale',
    state: 'OR',
    zipcode: '97365',
    country: 'USA',
    reputation: 99,
    completedTransactions: 30,
  },
  {
    id: 'user-6',
    name: 'Fiona',
    email: 'fiona@circula.demo',
    password: 'password123',
    address: '333 Cedar Blvd',
    city: 'Oakdale',
    state: 'OR',
    zipcode: '97365',
    country: 'USA',
    reputation: 90,
    completedTransactions: 5,
  },
  {
    id: 'user-7',
    name: 'George',
    email: 'george@circula.demo',
    password: 'password123',
    address: '444 Elm St',
    city: 'Greenwood',
    state: 'WA',
    zipcode: '98103',
    country: 'USA',
    reputation: 96,
    completedTransactions: 18,
  },
  {
    id: 'user-8',
    name: 'Hannah',
    email: 'hannah@circula.demo',
    password: 'password123',
    address: '555 Willow Way',
    city: 'Willowbrook',
    state: 'TX',
    zipcode: '77494',
    country: 'USA',
    reputation: 97,
    completedTransactions: 14,
  },
  {
    id: 'user-9',
    name: 'Ian',
    email: 'ian@circula.demo',
    password: 'password123',
    address: '666 Aspen Ct',
    city: 'Willowbrook',
    state: 'TX',
    zipcode: '77494',
    country: 'USA',
    reputation: 93,
    completedTransactions: 9,
  },
  {
    id: 'user-10',
    name: 'Julia',
    email: 'julia@circula.demo',
    password: 'password123',
    address: '777 Spruce Ave',
    city: 'Maple Creek',
    state: 'CA',
    zipcode: '95553',
    country: 'USA',
    reputation: 99,
    completedTransactions: 25,
  },
  {
    id: 'user-11',
    name: 'Kevin',
    email: 'kevin@circula.demo',
    password: 'password123',
    address: '888 Redwood Pkwy',
    city: 'Oakdale',
    state: 'OR',
    zipcode: '97365',
    country: 'USA',
    reputation: 94,
    completedTransactions: 11,
  },
  {
    id: 'user-12',
    name: 'Laura',
    email: 'laura@circula.demo',
    password: 'password123',
    address: '999 Sequoia Cir',
    city: 'Greenwood',
    state: 'WA',
    zipcode: '98103',
    country: 'USA',
    reputation: 100,
    completedTransactions: 40,
  },
];
